import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import ClientComponent from './client-component'
import ServerComponent from './server-component'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <div>
          <h2>API</h2>
          <ClientComponent>
            <ServerComponent />
          </ClientComponent>
        </div>
      </body>
    </html>
  )
}
